title: Scripts
modelClass: Shohabbos\ScriptShop\Models\Script
list: $/shohabbos/scriptshop/models/script/columns.yaml
recordUrl: 'shohabbos/scriptshop/scripts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
